### ISSUE TITLE
what am i missing. getting no valid crumb included

### ISSUE THREAD

**Issue by jasonlang80** [janjoerke/vscode-jenkins-pipeline-linter-connector#1]
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /. Reason:
<pre>    No valid crumb was included in the request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>

**Comment by janjoerke** [comment]
Hi Jason,

did you configure the following configuration settings?

- jenkins.pipeline.linter.connector.url
- jenkins.pipeline.linter.connector.user (only, if your jenkins server requires authentication)
- jenkins.pipeline.linter.connector.pass (only, if your jenkins server requires authentication)

The extension uses the credentials for a basic authentication (https://de.wikipedia.org/wiki/HTTP-Authentifizierung) with the jenkins server. I am no expert on jenkins security, but if i were to guess, i could think that maybe your server may not allow basic auth and thererfore reject the request.

**Comment by jasonlang80** [comment]
Yes, I have all 3 of those set. However, my server has CSRF Protection enabled. I think your plugin may not function correctly with it.

**Comment by janjoerke** [comment]
I´ve released a new version (1.1.0) with support for Jenkins Server with CRSF protection. To use it you have to specify the crumb issuing url of Jenkins:

"jenkins.pipeline.linter.connector.crumbUrl": "http://<your_jenkins_server:port>/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb))"

My jenkins installation with activated CRSF did not reject me before, so i am not 100% sure that this will work on first try. We´ll have to see.

**Comment by jasonlang80** [comment]
That Worked Great for me! 
Thank you for your quick turn around on this.

**Comment by janjoerke** [comment]
From the Menu: File --> Preferences --> Settings
And then: Extensions --> Jenkins Pipeline Linter Connector

Adjust the example parameter in the comment to match your system.

Am Mi., 10. Okt. 2018 um 12:25 Uhr schrieb syntax-ops <
notifications@github.com>:

**Comment by IgorOhrimenko** [comment]
I am using localhost:8080 and Crumb always return 403.
[Resolved this problem disable CSRF.](https://www.jenkins.io/doc/book/security/csrf-protection/#disabling-csrf-protection)
