### ISSUE TITLE
Settings question

### ISSUE THREAD

**Issue by DavidA2014** [janjoerke/vscode-jenkins-pipeline-linter-connector#12]
Hi, I have installed v.1.1.7 of the plugin, using VS Code 1.32.3. When I attempt to set the settings I get:

    Unable to write to User Settings because jenkins.pipeline.linter.connector.url is not a registered configuration.

Any idea why this might be?

What are the minimum settings required for this plugin?

**Comment by janjoerke** [comment]
Hi, right now i have no clue. I am also using VS Code 1.32.3 and 1.1.7 without any problems. 

Please compare your settings with the one below. This should work.

```
{
    "jenkins.pipeline.linter.connector.url": "http://<your_server>:<port>/pipeline-model-converter/validate"
}
```

**Comment by DavidA2014** [comment]
Thanks, that almost works.  With "jenkins.pipeline.linter.connector.url" specified (and no other urls) I see error:

    Error: unable to verify the first certificate

Our internal servers use certificates. Do you know how I can satisfy the certificate requirement in VS Code and this extension?

**Comment by janjoerke** [comment]
For me, it is very difficult to debug a foreign system, because of access and time constraints.

You can try: "jenkins.pipeline.linter.connector.strictssl": false
Maybe this helps.

If not, you could try to find a solution by yourself by forking the project and issue a merge request if you succeed.

**Comment by DavidA2014** [comment]
Thank you, setting strictssl to false worked around the problem.

Please will you explain the purpose of the crumb url?

**Comment by janjoerke** [comment]
That is a feature protecting against [CSRF](https://de.wikipedia.org/wiki/Cross-Site-Request-Forgery).

Basically, you call your server once, to request a crumb and then use this crumb to verify subsequent requests.

**Comment by DavidA2014** [comment]
Thanks for your help. It is working nicely now.

**Comment by kennywuu** [comment]
Hi, 
I meet the same problem, 
"Error: unable to verify the first certificate"

 setting strictssl to false, does not work for me. 
do you have any suggetions ?

Thanks!
