### ISSUE TITLE
Error using https

### ISSUE THREAD

**Issue by FROSADO** [janjoerke/vscode-jenkins-pipeline-linter-connector#2]
If the Jenkins server is running using https, the plugin is unable to validate the code.

setting Example: 
`"jenkins.pipeline.linter.connector.crumbUrl": "https://jenkins.domain.server/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,%22:%22,//crumb)",`
`"jenkins.pipeline.linter.connector.url": "https://jenkins.domain.server/pipeline-model-converter/validate",`

> _Error: unable to verify the first certificate_

**Comment by FROSADO** [comment]
OK, it is aproblem related with VS Code. Solved setting this environment variable
`NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by FROSADO** [comment]
`NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by kennywuu** [comment]
Hi, 
Where can we set the "NODE_TLS_REJECT_UNAUTHORIZED=0", 
I cannot find out it in VS Code
