### ISSUE TITLE
Command 'Validate Jenkinsfile' resulted in an error (Cannot convert undefined or null to object)

### ISSUE THREAD

**Issue by darth-hp** [janjoerke/vscode-jenkins-pipeline-linter-connector#27]
Tried to run F1->Validate Jenkinsfile which resulted in "`Command 'Validate Jenkinsfile' resulted in an error (Cannot convert undefined or null to object)`". I configured settings but got no clue what's happening.

**Comment by timnee** [comment]
I'm getting the same error when I'm trying to use token authentication.   The workaround for me was to put the token as the password. see https://github.com/janjoerke/vscode-jenkins-pipeline-linter-connector/issues/19#issuecomment-596307978

**Comment by ohartl** [comment]
Would be fixed by #31

**Comment by JoSSte** [comment]
> I'm getting the same error when I'm trying to use token authentication. The workaround for me was to put the token as the password. see [#19 (comment)](https://github.com/janjoerke/vscode-jenkins-pipeline-linter-connector/issues/19#issuecomment-596307978)

I had the same issue today - maybe the documentation should be updated

**Comment by ghost** [comment]
Using this plugin puts me to this issue. Filling my Jenkins token in the `Pass` configuration field fires validation (https://github.com/janjoerke/vscode-jenkins-pipeline-linter-connector/issues/27#issuecomment-721766698) while in `Token` raises the error. v1.2.0, in WSL. 🤷‍♂️ Jenkins 2.452.1.
