### ISSUE TITLE
Error: unable to verify the first certificate for jenkins urls with https

### ISSUE THREAD

**Issue by TristanFAURE** [janjoerke/vscode-jenkins-pipeline-linter-connector#3]
Hello 
thanks for this extension !

I am testing the 1.1.2 
my jenkins is connected through https and when I run the validation I got : "Error: unable to verify the first certificate"

how can i fix that ? is it possible to set a strict-ssl parameter to false ?

Regards

**Comment by janjoerke** [comment]
Hello, i am not sure right now. I hope I will find some time on Monday to look into it. 
Sadly I have no server with a certificate on hand to test it, so I would really appreciate your support here.

I will update the issue, when I know more.

**Comment by janjoerke** [comment]
I have added an option for disabling strict ssl validation. You can find the changes in  the branch:

feature/strictssl

https://github.com/janjoerke/vscode-jenkins-pipeline-linter-connector/tree/feature/strictssl

Please checkout this branch, open the folder with VSCode and start a Debugging Session (F5) to try this change with your server.

If it works for you, i will incorporate the change in the next release, if not we´ll have to dig further.

**Comment by TristanFAURE** [comment]
I would be able to test it next week. Thank you for the change

**Comment by cvakiitho** [comment]
Hi, I have the same problem, I tried opening this branch in VSCode -> F5, and it just stops the debugging process right away, with nothing interesting in debug console.

**Comment by TristanFAURE** [comment]
Hi, I've checkout the branch but with my company I can't install the vscode dependency. Does somebody can zip me the node_modules folder ?

**Comment by cvakiitho** [comment]
https://sap-my.sharepoint.com/:u:/p/tomas_hartmann/ESWqROKrR6pJgUsWX1s_fmwBDonbxMZN-LNI3ZCozEqV_A?e=YRys0J

**Comment by janjoerke** [comment]
I released 1.1.3, which contains the changes. Thank you for your assistance.
