### ISSUE TITLE
Runtime validation.

### ISSUE THREAD

**Issue by shashikumaarb** [janjoerke/vscode-jenkins-pipeline-linter-connector#7]
Hi how do I debug the jenkins.groovy file.
this extension is basically validating that if the file is syntactically correct or not but does not catch run time exception.

e.g. this script is valid but when I run this in jenkins it errors because the csproj isn't right xml doc.

#!groovy

def WORKSPACE = env.WORKSPACE
def VERSION = "1.5.0"   //maintain version here

node('Windows') {     //this instructs Jenkins to use the agent with label 'Windows' (exact spelling)  
    
	
        def checkoutscm = checkout scm  //clone the repository
        echo "SCM checkout: ${checkoutscm}"
		echo "VERSION before is ${VERSION}"
		def files = bat(script: "dir core", returnStdout: true)
		echo "Files: ${files}"
		def csprojFile = readFile("${env.WORKSPACE}/Core/Core.csproj");
		echo "csprojFile: ${csprojFile}"
		def xml = new XmlSlurper().parse(csprojFile)		
		/*VERSION = xml.PropertyGroup.Version.text()*/
		echo "VERSION after is ${VERSION}"
        def NUGET_PATH = env.NUGET_PATH
		echo "SEMVER is: ${SEMVER}"
}  
error:
java.net.MalformedURLException: no protocol: <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>Aim.Cohesion.Core</AssemblyName>
    <RootNamespace>Aim.Cohesion.Core</RootNamespace>
    <Version>1.1.3</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GlobalAspects.cs" Link="GlobalAspects.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Standard\Standard.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="2.0.0" />
    <PackageReference Include="StructureMap.Microsoft.DependencyInjection" Version="1.4.0" />
    <PackageReference Include="System.Security.Principal.Windows" Version="4.4.1" />
  </ItemGroup>

</Project>

	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)

**Comment by janjoerke** [comment]
Hi, this extension does not validate the groovy script on its own. It´s only purpose is to send the Jenkinsfile from within VS Code to the Jenkins server, so that you don´t have to send it by yourself. The validation takes place on the Jenkins server.
